[
  {
    photo: "https://i.ibb.co/SrpxwJs/1.jpg",
    propertyName: "Cozy Modern House with Plenty of Room",
    guests: 6,
    beds: 6,
    bath: 4,
    description: "",
    location: "Los Angeles, California, United States of America",
    postedBy: "Sarah Bowens",
  },
  {
    photo: "https://i.ibb.co/n883zYk/2.jpg",
    propertyName: "Cozy Modern House with Plenty of Room",
    guests: 6,
    beds: 6,
    bath: 4,
    description: "",
    location: "Los Angeles, California, United States of America",
    postedBy: "Sarah Bowens",
  },
  {
    photo: "https://i.ibb.co/g4c3n02/3.jpg",
    propertyName: "Cozy Modern House with Plenty of Room",
    guests: 6,
    beds: 6,
    bath: 4,
    description: "",
    location: "Los Angeles, California, United States of America",
    postedBy: "Sarah Bowens",
  },
  {
    photo: "https://i.ibb.co/LJhSdBb/4.jpg",
    propertyName: "Cozy Modern House with Plenty of Room",
    guests: 6,
    beds: 6,
    bath: 4,
    description: "",
    location: "Los Angeles, California, United States of America",
    postedBy: "Sarah Bowens",
  },
  {
    photo: "https://i.ibb.co/JkNjhY4/5.jpg",
    propertyName: "Cozy Modern House with Plenty of Room",
    guests: 6,
    beds: 6,
    bath: 4,
    description: "",
    location: "Los Angeles, California, United States of America",
    postedBy: "Sarah Bowens",
  },
  {
    photo: "https://i.ibb.co/HhvFrDp/7.jpg",
    propertyName: "Cozy Modern House with Plenty of Room",
    guests: 6,
    beds: 6,
    bath: 4,
    description: "",
    location: "Los Angeles, California, United States of America",
    postedBy: "Sarah Bowens",
  },
  {
    photo: "https://i.ibb.co/SrpxwJs/1.jpg",
    propertyName: "Cozy Modern House with Plenty of Room",
    guests: 6,
    beds: 6,
    bath: 4,
    description: "",
    location: "Los Angeles, California, United States of America",
    postedBy: "Sarah Bowens",
  },
  {
    photo: "https://i.ibb.co/SrpxwJs/1.jpg",
    propertyName: "Cozy Modern House with Plenty of Room",
    guests: 6,
    beds: 6,
    bath: 4,
    description: "",
    location: "Los Angeles, California, United States of America",
    postedBy: "Sarah Bowens",
  },
  {
    photo: "https://i.ibb.co/SrpxwJs/1.jpg",
    propertyName: "Cozy Modern House with Plenty of Room",
    guests: 6,
    beds: 6,
    bath: 4,
    description: "",
    location: "Los Angeles, California, United States of America",
    postedBy: "Sarah Bowens",
  },
  {
    photo: "https://i.ibb.co/SrpxwJs/1.jpg",
    propertyName: "Cozy Modern House with Plenty of Room",
    guests: 6,
    beds: 6,
    bath: 4,
    description: "",
    location: "Los Angeles, California, United States of America",
    postedBy: "Sarah Bowens",
  },
];
