[
  {
    photo: "https://i.ibb.co/SrpxwJs/1.jpg",
    propertyName: "Cozy Modern House with Plenty of Room",
    guests: 15,
    beds: 6,
    bath: 4,
    description: "Conveniently located, bright, modern and large 2BR Nob Hill apartment. One block from restaurants, coffee shops, grocery stores, anything. Great short-term rental for relocating professionals or as temporary corporate housing.

    Quiet/nice area, away from the TenderNob riff-raff | Walk to work in the FiDi or SOMA (or work from home w/ desk!) | Whole Foods and Trader Joes easy walking distance | Coffee shops within one block | 15 restaurants within 1-2 blocks | 40 restaurants within three blocks.",
    location: "Los Angeles, California, United States of America",
    postedBy: "Sarah Bowens",
  },
  {
    photo: "https://i.ibb.co/n883zYk/2.jpg",
    propertyName: "House with deck and views",
    guests: 10,
    beds: 3,
    bath: 2,
    description: "The house has a beautiful panoramic view of the city. It is located in a quiet and upscale neighborhood of San Francisco. It comes with three bedrooms on one level, and one more bedroom in the lower level.
    Next door to the famous Haight Ashbury and beautiful Cole Valley neighborhoods. The Haight-Ashbury district only a few blocks away is noted for its role as a center of the 1960s hippie movement. Cole Valley district is also a few blocks away with it’s nice restaurants, boulangeries, cafes",
    location: "Los Gatos, California, United States of America",
    postedBy: "Jonathan Vickers",
  },
  {
    photo: "https://i.ibb.co/g4c3n02/3.jpg",
    propertyName: "Authentic San Francisco with Modern Comfort",
    guests: 8,
    beds: 3,
    bath: 2,
    description: "Live authentically - and comfortably - in this 1894 San Francisco flat which has architectural details intact but with modern comforts. This Victorian 3-bedroom flat is roomy and light with all systems updated. The Castro is sunny, central and safe. Enjoy lounging on the deck or making dinner in the renovated kitchen. Everything you need is there! Oh, yes, and parking is also included.",
    location: "San Francisco, California, United States of America",
    postedBy: "Ashley Moreno",
  },
  {
    photo: "https://i.ibb.co/LJhSdBb/4.jpg",
    propertyName: "Bright Family Friendly Home on Tree-Lined Street",
    guests: 6,
    beds: 3,
    bath: 2,
    description: "This home is located in preferred west Menlo Park with an impressive open concept floor plan. Newly remodeled throughout with clean lines,high ceilings,designer touches, and modern amenities.
    Spacious kitchen with stunning quarter counter tops, expansive island with seating, and new appliances. Family room with sliding doors to backyard is perfect for indoor-outdoor entertaining.
    Walk or ride one of our bikes to downtown Menlo Park and Stanford University, a track, field.",
    location: "Seattle, Washington, United States of America",
    postedBy: "Terrence Man",
  },
  {
    photo: "https://i.ibb.co/JkNjhY4/5.jpg",
    propertyName: "Brand new luxury house near high tech companies",
    guests: 8,
    beds: 3,
    bath: 2,
    description: "Welcome to our completely remodeled guest house with modern luxury furnishings, dedicated parking, business class Internet, Wifi 6 coverage. Centrally located in the heart of silicon valley, walking distance to coffee shops, restaurants, grocery stores, Caltrain station and minutes away from SJC, Convention Center, SAP Center, Levi's Stadium, and downtown San Jose!
    We are committed to make sure your stay is enjoyable so please don't hesitate to reach out if you need anything!",
    location: "San Jose, California, United States of America",
    postedBy: "Lucy Lee",
  },
  {
    photo: "https://i.ibb.co/HhvFrDp/7.jpg",
    propertyName: "Spacious 4BR Flat, in Milpitas",
    guests: 10,
    beds: 4,
    bath: 2,
    description: "This is spacious main level flat with 4BD/2BA, living room, & kitchen. The Sunset is a more residential area of Milpitas, making it a great place for families or those who want to stay away from the bustling downtown area, yet still only 25 minutes away from it.",
    location: "Milpitas, California, United States of America",
    postedBy: "Michael Van Peoples",
  },
  {
    photo: "https://i.ibb.co/jzS2tSD/sidekix-media-1v-Mz2-Mclr-M-unsplash.jpg",
    propertyName: "Luxurious Mediterranean Villa w/Panoramic Views",
    guests: 12,
    beds: 4,
    bath: 3,
    description: "Gorgeous Mediterrannean style charmer features a main house w/high ceilings, a huge outdoor dining patio, an amazing 2nd floor balcony w/ incredible views, backyard + front yard chill areas. A true chef's kitchen complete w/a professional Subzero fridge & Wolf Range. Moroccan + Mediterranean style through w/arched French windows , medieval lighting, & unique Art Deco style baths. Formal dining seats 8 + outdoor dining for 8, breakfast nook +more outdoor seating.",
    location: "San Diego, California, United States of America",
    postedBy: "Terry Lin",
  },
  {
    photo: "https://i.ibb.co/R09cTxn/webaliser-TPTXZd9m-Oo-unsplash.jpg",
    propertyName: "Lovely 5BR 5BA Home - Steps to LACC, Sleeps 10",
    guests: 10,
    beds: 5,
    bath: 5,
    description: "This place is located 5 mins away from Los Angeles Convention Center, 7 mins to GRAMMY Museum L.A. Live, 8 mins to The Broad, 9 mins to California Science Center, 9 mins to Natural History Museum of Los Angeles County (NHM), 21 mins to Hollywood Walk of Fame, 23 mins to Ripley's Believe It or Not!, 27 mins to Santa Monica State Beach. There are also restaurants and shops located nearby!",
    location: "Santa Clarita, California, United States of America",
    postedBy: "Otha Park",
  },
  {
    photo: "https://i.ibb.co/k9V99v3/brian-babb-Xbw-Hrt87m-Q0-unsplash.jpg",
    propertyName: "Mid-City Hayward Home w/Pool + Hot Tub",
    guests: 12,
    beds: 5,
    bath: 3,
    description: "We are in the best neighborhood in Hayward -walking distance to Grove Shopping Area, the Farmers Market, the Beverly Shopping Center & Beverly Center Shopping Mall. Germ Free - Superior Cleaning-Our home has a beautiful pool (fence around the pool) area w/hot tub, outdoor living area, basketball court, & BBQ. Inside we have all the modern amenities, including a unique, very large"steam bath" for 5 people. Parking for 4 cars w/covered top. Not a Party House-Surveillance Used",
    location: "Hayward, California, United States of America",
    postedBy: "Mitchell Nickerson",
  },
  {
    photo: "https://i.ibb.co/bXpfh6S/kara-eads-L7-Ew-Hkq1-B2s-unsplash.jpg",
    propertyName: "A Luxury Home with Pool, Spa, and Mini-Golf",
    guests: 10,
    beds: 4,
    bath: 3,
    description: "Over 3000 sf 4BR/3 BA house with a swimming pool, outdoor spa, mini golf, open floor plan, high ceiling living room, waterfall, BBQ, Jacuzzi in Master Bathroom, plenty of parking, and walking distance to grocery stores and restaurants. Cable (150 channels), HBO, Showtime, Netflix, and Amazon Prime Video. Ideal for couples, families, and business travelers.",
    location: "Palo Alto, California, United States of America",
    postedBy: "Hope Parker",
  },
];
